-- Migration to add all supplier contact form fields to suppliers table
-- Run this in your Supabase SQL editor

ALTER TABLE public.suppliers 
ADD COLUMN IF NOT EXISTS dba text,
ADD COLUMN IF NOT EXISTS physical_address text,
ADD COLUMN IF NOT EXISTS mailing_address text,
ADD COLUMN IF NOT EXISTS payment_terms_net30 boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS payment_terms_net60 boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS payment_terms_net90 boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS payment_terms_discount_percent numeric(5,2),
ADD COLUMN IF NOT EXISTS payment_terms_discount_days integer,
ADD COLUMN IF NOT EXISTS account_rep_name text,
ADD COLUMN IF NOT EXISTS account_rep_email text,
ADD COLUMN IF NOT EXISTS account_rep_office_phone text,
ADD COLUMN IF NOT EXISTS account_rep_cell_phone text,
ADD COLUMN IF NOT EXISTS gfsi_certification_held boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gfsi_cert_name text,
ADD COLUMN IF NOT EXISTS ap_rep_name text,
ADD COLUMN IF NOT EXISTS ap_rep_email text,
ADD COLUMN IF NOT EXISTS ap_rep_office_phone text,
ADD COLUMN IF NOT EXISTS ap_rep_cell_phone text,
ADD COLUMN IF NOT EXISTS qa_rep_name text,
ADD COLUMN IF NOT EXISTS qa_rep_email text,
ADD COLUMN IF NOT EXISTS qa_rep_office_phone text,
ADD COLUMN IF NOT EXISTS qa_rep_cell_phone text,
ADD COLUMN IF NOT EXISTS emergency_contact_name text,
ADD COLUMN IF NOT EXISTS emergency_contact_email text,
ADD COLUMN IF NOT EXISTS emergency_contact_office_phone text,
ADD COLUMN IF NOT EXISTS emergency_contact_cell_phone text,
ADD COLUMN IF NOT EXISTS purchase_approval_required boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS purchase_approval_documents_received boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS purchase_approval_determination text,
ADD COLUMN IF NOT EXISTS approved_by text;
